# Generated by Django 2.1.4 on 2022-05-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Links',
        ),
    ]
